// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcSuhzYlICFUVqTfjIQ876emvrvAHMJ5E',
    appId: '1:907008505189:web:734a3f01afbc3d34d99d8c',
    messagingSenderId: '907008505189',
    projectId: 'note-app-518fd',
    authDomain: 'note-app-518fd.firebaseapp.com',
    storageBucket: 'note-app-518fd.appspot.com',
    measurementId: 'G-0YD9GYTBQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmmyijY8KgptfzkgPTRWr4iQBtrXuw1ck',
    appId: '1:907008505189:android:0b7de20b7897eb6cd99d8c',
    messagingSenderId: '907008505189',
    projectId: 'note-app-518fd',
    storageBucket: 'note-app-518fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbUAu6yTzdpPqCc5ccnX86z8VHuuw7rkY',
    appId: '1:907008505189:ios:27dc07a139eb8993d99d8c',
    messagingSenderId: '907008505189',
    projectId: 'note-app-518fd',
    storageBucket: 'note-app-518fd.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbUAu6yTzdpPqCc5ccnX86z8VHuuw7rkY',
    appId: '1:907008505189:ios:27dc07a139eb8993d99d8c',
    messagingSenderId: '907008505189',
    projectId: 'note-app-518fd',
    storageBucket: 'note-app-518fd.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );
}
